name: Tests

on:
  pull_request:
    branchs: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run:
          composer update

      - name: Composer normalize
        run:
          composer normalize --dry-run --indent-size=4 --indent-style=space

      - name: Coding Licensing
        run:
          vendor/bin/php-cs-fixer fix -vvv

      - name: PHPMD
        run:
          vendor/bin/phpmd app xml phpmd.xml

      - name: PHPStan
        run:
          vendor/bin/phpstan analyse -vvv

      - name: PHPUnit
        run:
          vendor/bin/phpunit --verbose

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
