name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run:
          composer update

      - name: Composer normalize
        run:
          composer normalize --dry-run --indent-size=4 --indent-style=space

      - name: Coding Licensing
        run:
          vendor/bin/php-cs-fixer fix -vvv

      - name: PHPMD
        run:
          vendor/bin/phpmd app xml phpmd.xml

      - name: PHPStan
        run:
          vendor/bin/phpstan analyse -vvv

      - name: PHPUnit
        run:
          vendor/bin/phpunit --verbose

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
    	  php-coveralls --coverage_clover=build/logs/clover.xml -v
